# Generated by Django 4.2.11 on 2025-03-08 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pending_visitor',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('CHECKOUT', 'Checkout'), ('DECLINED', 'Declined')], default='PENDING', max_length=15),
        ),
    ]
